// build.js: concatenates modules/ into background.js.
// Run with: node build.js
// Do this any time you edit a file in modules/ before reloading the extension.

const fs = require("fs");
const path = require("path");

const MODULES = [
  // Polyfill first: modules call chrome.* at load time, so the namespace
  // has to exist before any of them run.
  "browser-polyfill.js",
  "modules/classifier.js",
  "modules/sort.js",
  "modules/ai.js",
  "modules/actions.js",
  "modules/stacklet.js",
  "modules/features.js",
];

const out = [
  "// background.js — generated by build.js, do not edit directly.",
  "// Edit files in modules/ then run: node build.js",
  "",
];

for (const mod of MODULES) {
  const src = fs.readFileSync(mod, "utf-8").trim();
  out.push(`\n// ===== ${mod} =====\n`);
  out.push(src);
  out.push("");
}

const result = out.join("\n");
fs.writeFileSync("background.js", result, "utf-8");
console.log(`background.js rebuilt (${result.split("\n").length} lines)`);